apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: carrental
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/car_rental_system?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "app"
  SERVER_PORT: "8080"
  VARIANT_DIR: "/app/files/variant-image"
  LICENSE_DIR: "/app/files/license-image"
